In [1]:
import pandas as pd

# Read a .csv from a URL with Pandas

Target website: https://www.football-data.co.uk/data.php

In [2]:
# reading 1 csv file from the website
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [3]:
# showing dataframe
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,E0,23/01/2022,14:00,Arsenal,Burnley,0,0,D,0,0,...,2.32,-1.50,1.92,2.01,1.93,2.00,1.93,2.11,1.90,1.98
211,E0,23/01/2022,14:00,Crystal Palace,Liverpool,1,3,A,0,2,...,2.11,1.00,1.96,1.97,1.94,1.97,2.07,2.02,1.92,1.96
212,E0,23/01/2022,14:00,Leicester,Brighton,1,1,D,0,0,...,2.10,0.00,1.92,2.01,1.93,1.99,1.94,2.13,1.87,2.01
213,E0,23/01/2022,16:30,Chelsea,Tottenham,2,0,H,0,0,...,1.84,-0.75,1.99,1.94,1.97,1.95,2.03,2.07,1.96,1.92
214,E0,05/02/2022,18:00,Burnley,Watford,0,0,D,0,0,...,1.73,-0.25,1.90,2.00,1.89,2.03,1.93,2.07,1.87,2.01

In [4]:
# rename columns
df_premier21 = df_premier21.rename(columns={'Date':'date',
                                            'HomeTeam':'home_team',
                                            'AwayTeam':'away_team',
                                            'FTHG': 'home_goals',
                                            'FTAG': 'away_goals'})

In [5]:
# show dataframe
df_premier21

,Div,date,Time,home_team,away_team,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,E0,23/01/2022,14:00,Arsenal,Burnley,0,0,D,0,0,...,2.32,-1.50,1.92,2.01,1.93,2.00,1.93,2.11,1.90,1.98
211,E0,23/01/2022,14:00,Crystal Palace,Liverpool,1,3,A,0,2,...,2.11,1.00,1.96,1.97,1.94,1.97,2.07,2.02,1.92,1.96
212,E0,23/01/2022,14:00,Leicester,Brighton,1,1,D,0,0,...,2.10,0.00,1.92,2.01,1.93,1.99,1.94,2.13,1.87,2.01
213,E0,23/01/2022,16:30,Chelsea,Tottenham,2,0,H,0,0,...,1.84,-0.75,1.99,1.94,1.97,1.95,2.03,2.07,1.96,1.92
214,E0,05/02/2022,18:00,Burnley,Watford,0,0,D,0,0,...,1.73,-0.25,1.90,2.00,1.89,2.03,1.93,2.07,1.87,2.01

# Read HTML

Target Website: https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes_(seasons_1%E2%80%9320)

In [6]:
simpsons = pd.read_html('https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes_(seasons_1%E2%80%9320)')

In [7]:
simpsons[1].head()

,No.overall,No. inseason,Title,Directed by,Written by,Original air date,Prod.code,U.S. viewers(millions)
0,1,1,"""Simpsons Roasting on an Open Fire""",David Silverman,Mimi Pond,"December 17, 1989",7G08,26.7[46]
1,2,2,"""Bart the Genius""",David Silverman,Jon Vitti,"January 14, 1990",7G02,24.5[46]
2,3,3,"""Homer's Odyssey""",Wesley Archer,Jay Kogen & Wallace Wolodarsky,"January 21, 1990",7G03,27.5[47]
3,4,4,"""There's No Disgrace Like Home""",Gregg Vanzo & Kent Butterworth,Al Jean & Mike Reiss,"January 28, 1990",7G04,20.2[48]
4,5,5,"""Bart the General""",David Silverman,John Swartzwelder,"February 4, 1990",7G05,27.1[49]